a= int(input("enter any number:"))
b= int(input("enter any number:"))
print("sum:", a + b)
print("sub:", a - b)
print("multiply:", a*b)
print("float division:", a/b)
print("remainder", a%b)
print("floor division", a//b)
print("power",a**b)
